<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('barang')->insert([
            [
                'kode'        => 'BRG-202609-0001',
                'nama'        => 'Blouse Casual Cotton',
                'lingkar'     => 98,
                'panjang'     => 65,
                'kategori'    => 'Blouse',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0002',
                'nama'        => 'Kemeja Slim Fit Polos',
                'lingkar'     => 102,
                'panjang'     => 72,
                'kategori'    => 'Kemeja',
                'status'      => 'Terjual',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0003',
                'nama'        => 'Rok Plisket Panjang',
                'lingkar'     => 70,
                'panjang'     => 92,
                'kategori'    => 'Rok',
                'status'      => 'Draft',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0004',
                'nama'        => 'Celana Chino Reguler',
                'lingkar'     => 82,
                'panjang'     => 100,
                'kategori'    => 'Celana',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0005',
                'nama'        => 'Overall Denim Style',
                'lingkar'     => 96,
                'panjang'     => 130,
                'kategori'    => 'Overall',
                'status'      => 'Terjual',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0006',
                'nama'        => 'Outher Cardigan Rajut',
                'lingkar'     => 110,
                'panjang'     => 70,
                'kategori'    => 'Outher',
                'status'      => 'Draft',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0007',
                'nama'        => 'Jaket Parka Canvas',
                'lingkar'     => 114,
                'panjang'     => 75,
                'kategori'    => 'Jaket',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0008',
                'nama'        => 'Vest Formal Tailored',
                'lingkar'     => 94,
                'panjang'     => 60,
                'kategori'    => 'Vest',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0009',
                'nama'        => 'Gamis Syari Premium',
                'lingkar'     => 105,
                'panjang'     => 138,
                'kategori'    => 'Gamis',
                'status'      => 'Terjual',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0010',
                'nama'        => 'Dress Elegant Midi',
                'lingkar'     => 92,
                'panjang'     => 115,
                'kategori'    => 'Dress',
                'status'      => 'Draft',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0011',
                'nama'        => 'Blouse Ruffle Silk',
                'lingkar'     => 95,
                'panjang'     => 63,
                'kategori'    => 'Blouse',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0012',
                'nama'        => 'Kemeja Flanel Kotak',
                'lingkar'     => 106,
                'panjang'     => 74,
                'kategori'    => 'Kemeja',
                'status'      => 'Terjual',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0013',
                'nama'        => 'Rok A-Line Linen',
                'lingkar'     => 74,
                'panjang'     => 88,
                'kategori'    => 'Rok',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0014',
                'nama'        => 'Celana Highwaist Cullote',
                'lingkar'     => 78,
                'panjang'     => 98,
                'kategori'    => 'Celana',
                'status'      => 'Draft',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0015',
                'nama'        => 'Overall Corduroy Jumper',
                'lingkar'     => 100,
                'panjang'     => 132,
                'kategori'    => 'Overall',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0016',
                'nama'        => 'Outher Kimono Linen',
                'lingkar'     => 112,
                'panjang'     => 68,
                'kategori'    => 'Outher',
                'status'      => 'Terjual',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0017',
                'nama'        => 'Jaket Bomber Oversized',
                'lingkar'     => 118,
                'panjang'     => 71,
                'kategori'    => 'Jaket',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0018',
                'nama'        => 'Vest Knit Crop',
                'lingkar'     => 90,
                'panjang'     => 52,
                'kategori'    => 'Vest',
                'status'      => 'Draft',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0019',
                'nama'        => 'Gamis Brokat Modern',
                'lingkar'     => 102,
                'panjang'     => 140,
                'kategori'    => 'Gamis',
                'status'      => 'Tersedia',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kode'        => 'BRG-202609-0020',
                'nama'        => 'Dress Floral Maxidress',
                'lingkar'     => 98,
                'panjang'     => 128,
                'kategori'    => 'Dress',
                'status'      => 'Terjual',
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
        ]);
    }
}
