<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    public function run()
    {
        DB::table('barang')->insert([
            [
                'kode'         => 'BRG-202609-0001',
                'nama'         => 'Blouse Casual Cotton',
                'lingkar'      => 98,
                'panjang'      => 65,
                'kategori'     => 'Blouse',
                'harga_beli'   => 35000,
                'harga_jual'   => 65000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 1,
            ],
            [
                'kode'         => 'BRG-202609-0002',
                'nama'         => 'Kemeja Slim Fit Polos',
                'lingkar'      => 102,
                'panjang'      => 72,
                'kategori'     => 'Kemeja',
                'harga_beli'   => 40000,
                'harga_jual'   => 75000,
                'status'       => 'Terjual',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 2,
            ],
            [
                'kode'         => 'BRG-202609-0003',
                'nama'         => 'Rok Plisket Panjang',
                'lingkar'      => 70,
                'panjang'      => 92,
                'kategori'     => 'Rok',
                'harga_beli'   => 45000,
                'harga_jual'   => 80000,
                'status'       => 'Draft',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 3,
            ],
            [
                'kode'         => 'BRG-202609-0004',
                'nama'         => 'Celana Chino Reguler',
                'lingkar'      => 82,
                'panjang'      => 100,
                'kategori'     => 'Celana',
                'harga_beli'   => 50000,
                'harga_jual'   => 95000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 4,
            ],
            [
                'kode'         => 'BRG-202609-0005',
                'nama'         => 'Overall Denim Style',
                'lingkar'      => 96,
                'panjang'      => 130,
                'kategori'     => 'Overall',
                'harga_beli'   => 65000,
                'harga_jual'   => 120000,
                'status'       => 'Terjual',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 5,
            ],
            [
                'kode'         => 'BRG-202609-0006',
                'nama'         => 'Outher Cardigan Rajut',
                'lingkar'      => 110,
                'panjang'      => 70,
                'kategori'     => 'Outher',
                'harga_beli'   => 40000,
                'harga_jual'   => 75000,
                'status'       => 'Draft',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 6,
            ],
            [
                'kode'         => 'BRG-202609-0007',
                'nama'         => 'Jaket Parka Canvas',
                'lingkar'      => 114,
                'panjang'      => 75,
                'kategori'     => 'Jaket',
                'harga_beli'   => 85000,
                'harga_jual'   => 150000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 7,
            ],
            [
                'kode'         => 'BRG-202609-0008',
                'nama'         => 'Vest Formal Tailored',
                'lingkar'      => 94,
                'panjang'      => 60,
                'kategori'     => 'Vest',
                'harga_beli'   => 35000,
                'harga_jual'   => 65000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 8,
            ],
            [
                'kode'         => 'BRG-202609-0009',
                'nama'         => 'Gamis Syari Premium',
                'lingkar'      => 105,
                'panjang'      => 138,
                'kategori'     => 'Gamis',
                'harga_beli'   => 90000,
                'harga_jual'   => 165000,
                'status'       => 'Terjual',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 9,
            ],
            [
                'kode'         => 'BRG-202609-0010',
                'nama'         => 'Dress Elegant Midi',
                'lingkar'      => 92,
                'panjang'      => 115,
                'kategori'     => 'Dress',
                'harga_beli'   => 60000,
                'harga_jual'   => 110000,
                'status'       => 'Draft',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 10,
            ],
            [
                'kode'         => 'BRG-202609-0011',
                'nama'         => 'Blouse Ruffle Silk',
                'lingkar'      => 95,
                'panjang'      => 63,
                'kategori'     => 'Blouse',
                'harga_beli'   => 38000,
                'harga_jual'   => 70000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 11,
            ],
            [
                'kode'         => 'BRG-202609-0012',
                'nama'         => 'Kemeja Flanel Kotak',
                'lingkar'      => 106,
                'panjang'      => 74,
                'kategori'     => 'Kemeja',
                'harga_beli'   => 45000,
                'harga_jual'   => 85000,
                'status'       => 'Terjual',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 12,
            ],
            [
                'kode'         => 'BRG-202609-0013',
                'nama'         => 'Rok A-Line Linen',
                'lingkar'      => 74,
                'panjang'      => 88,
                'kategori'     => 'Rok',
                'harga_beli'   => 42000,
                'harga_jual'   => 78000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 13,
            ],
            [
                'kode'         => 'BRG-202609-0014',
                'nama'         => 'Celana Highwaist Cullote',
                'lingkar'      => 78,
                'panjang'      => 98,
                'kategori'     => 'Celana',
                'harga_beli'   => 48000,
                'harga_jual'   => 88000,
                'status'       => 'Draft',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 14,
            ],
            [
                'kode'         => 'BRG-202609-0015',
                'nama'         => 'Overall Corduroy Jumper',
                'lingkar'      => 100,
                'panjang'      => 132,
                'kategori'     => 'Overall',
                'harga_beli'   => 70000,
                'harga_jual'   => 130000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 15,
            ],
            [
                'kode'         => 'BRG-202609-0016',
                'nama'         => 'Outher Kimono Linen',
                'lingkar'      => 112,
                'panjang'      => 68,
                'kategori'     => 'Outher',
                'harga_beli'   => 42000,
                'harga_jual'   => 80000,
                'status'       => 'Terjual',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 16,
            ],
            [
                'kode'         => 'BRG-202609-0017',
                'nama'         => 'Jaket Bomber Oversized',
                'lingkar'      => 118,
                'panjang'      => 71,
                'kategori'     => 'Jaket',
                'harga_beli'   => 80000,
                'harga_jual'   => 145000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 17,
            ],
            [
                'kode'         => 'BRG-202609-0018',
                'nama'         => 'Vest Knit Crop',
                'lingkar'      => 90,
                'panjang'      => 52,
                'kategori'     => 'Vest',
                'harga_beli'   => 30000,
                'harga_jual'   => 55000,
                'status'       => 'Draft',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 18,
            ],
            [
                'kode'         => 'BRG-202609-0019',
                'nama'         => 'Gamis Brokat Modern',
                'lingkar'      => 102,
                'panjang'      => 140,
                'kategori'     => 'Gamis',
                'harga_beli'   => 95000,
                'harga_jual'   => 175000,
                'status'       => 'Tersedia',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 19,
            ],
            [
                'kode'         => 'BRG-202609-0020',
                'nama'         => 'Dress Floral Maxidress',
                'lingkar'      => 98,
                'panjang'      => 128,
                'kategori'     => 'Dress',
                'harga_beli'   => 65000,
                'harga_jual'   => 120000,
                'status'       => 'Terjual',
                'created_at'   => now(),
                'updated_at'   => now(),
                'pembelian_id' => 20,
            ],
        ]);
    }
}
