<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PembelianSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pembelian')->insert([
            [
                'tanggal'     => '2026-09-001',
                'kode'        => 'BEL-202609-0001',
                'total'       => 1500000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 1,
            ],
            [
                'tanggal'     => '2026-09-02',
                'kode'        => 'BEL-202609-0002',
                'total'       => 2300000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 2,
            ],
            [
                'tanggal'     => '2026-09-03',
                'kode'        => 'BEL-202609-0003',
                'total'       => 750000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 3,
            ],
            [
                'tanggal'     => '2026-09-04',
                'kode'        => 'BEL-202609-0004',
                'total'       => 3100000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 4,
            ],
            [
                'tanggal'     => '2026-09-05',
                'kode'        => 'BEL-202609-0005',
                'total'       => 1250000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 5,
            ],
            [
                'tanggal'     => '2026-09-06',
                'kode'        => 'BEL-202609-0006',
                'total'       => 4500000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 6,
            ],
            [
                'tanggal'     => '2026-09-07',
                'kode'        => 'BEL-202609-0007',
                'total'       => 890000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 7,
            ],
            [
                'tanggal'     => '2026-09-08',
                'kode'        => 'BEL-202609-0008',
                'total'       => 2100000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 8,
            ],
            [
                'tanggal'     => '2026-09-09',
                'kode'        => 'BEL-202609-0009',
                'total'       => 1750000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 9,
            ],
            [
                'tanggal'     => '2026-09-10',
                'kode'        => 'BEL-202609-0010',
                'total'       => 5000000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 10,
            ],
            [
                'tanggal'     => '2026-09-11',
                'kode'        => 'BEL-202609-0011',
                'total'       => 980000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 11,
            ],
            [
                'tanggal'     => '2026-09-12',
                'kode'        => 'BEL-202609-0012',
                'total'       => 3400000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 12,
            ],
            [
                'tanggal'     => '2026-09-13',
                'kode'        => 'BEL-202609-0013',
                'total'       => 1600000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 13,
            ],
            [
                'tanggal'     => '2026-09-14',
                'kode'        => 'BEL-202609-0014',
                'total'       => 2750000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 14,
            ],
            [
                'tanggal'     => '2026-09-15',
                'kode'        => 'BEL-202609-0015',
                'total'       => 6200000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 15,
            ],
            [
                'tanggal'     => '2026-09-16',
                'kode'        => 'BEL-202609-0016',
                'total'       => 1150000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 16,
            ],
            [
                'tanggal'     => '2026-09-17',
                'kode'        => 'BEL-202609-0017',
                'total'       => 4100000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 17,
            ],
            [
                'tanggal'     => '2026-09-18',
                'kode'        => 'BEL-202609-0018',
                'total'       => 850000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 18,
            ],
            [
                'tanggal'     => '2026-09-19',
                'kode'        => 'BEL-202609-0019',
                'total'       => 2900000,
                'status'      => 'Sudah Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 19,
            ],
            [
                'tanggal'     => '2026-09-20',
                'kode'        => 'BEL-202609-0020',
                'total'       => 1800000,
                'status'      => 'Belum Bayar',
                'created_at'  => now(),
                'updated_at'  => now(),
                'user_id'     => 1,
                'supplier_id' => 20,
            ],
        ]);
    }
}
