<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PenjualanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('penjualan')->insert([
            [
                'tanggal'       => '2026-10-01',
                'kode'          => 'JUA-202610-0001',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 1,
            ],
            [
                'tanggal'       => '2026-10-02',
                'kode'          => 'JUA-202610-0002',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 2,
            ],
            [
                'tanggal'       => '2026-10-03',
                'kode'          => 'JUA-202610-0003',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 3,
            ],
            [
                'tanggal'       => '2026-10-04',
                'kode'          => 'JUA-202610-0004',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 4,
            ],
            [
                'tanggal'       => '2026-10-05',
                'kode'          => 'JUA-202610-0005',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 5,
            ],
            [
                'tanggal'       => '2026-10-06',
                'kode'          => 'JUA-202610-0006',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 6,
            ],
            [
                'tanggal'       => '2026-10-07',
                'kode'          => 'JUA-202610-0007',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 7,
            ],
            [
                'tanggal'       => '2026-10-08',
                'kode'          => 'JUA-202610-0008',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 8,
            ],
            [
                'tanggal'       => '2026-10-09',
                'kode'          => 'JUA-202609-0009',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 9,
            ],
            [
                'tanggal'       => '2026-10-10',
                'kode'          => 'JUA-202610-0010',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 10,
            ],
            [
                'tanggal'       => '2026-10-11',
                'kode'          => 'JUA-202610-0011',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 11,
            ],
            [
                'tanggal'       => '2026-10-12',
                'kode'          => 'JUA-202610-0012',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 12,
            ],
            [
                'tanggal'       => '2026-10-13',
                'kode'          => 'JUA-202610-0013',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 13,
            ],
            [
                'tanggal'       => '2026-10-14',
                'kode'          => 'JUA-202610-0014',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 14,
            ],
            [
                'tanggal'       => '2026-10-15',
                'kode'          => 'JUA-202610-0015',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 15,
            ],
            [
                'tanggal'       => '2026-10-16',
                'kode'          => 'JUA-202610-0016',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 16,
            ],
            [
                'tanggal'       => '2026-10-17',
                'kode'          => 'JUA-202610-0017',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 17,
            ],
            [
                'tanggal'       => '2026-10-18',
                'kode'          => 'JUA-202610-0018',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 18,
            ],
            [
                'tanggal'       => '2026-10-19',
                'kode'          => 'JUA-202610-0019',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 19,
            ],
            [
                'tanggal'       => '2026-10-20',
                'kode'          => 'JUA-202610-0020',
                'ongkir'        => 15000,
                'status'        => 'Belum Bayar',
                'created_at'    => now(),
                'updated_at'    => now(),
                'user_id'       => 1,
                'pelanggan_id'  => 20,
            ],
        ]);
    }
}
